# Generated by Django 5.2.5 on 2025-09-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0003_progressvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressvideo',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressvideo',
            name='fps',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='progressvideo',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
