# Generated by Django 5.2.6 on 2025-09-13 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0004_progressvideo_end_date_progressvideo_fps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
