# Generated by Django 5.2.6 on 2025-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0005_progressvideo_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressvideo',
            old_name='public',
            new_name='is_public',
        ),
        migrations.AddField(
            model_name='progressimage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
