# Generated by Django 5.2.6 on 2025-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
