# Generated by Django 5.2.6 on 2025-09-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_date_joined'),
    ]

    operations = [
    ]
